package agent

import (
	"context"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	"github.com/openai/openai-go/v3/packages/param"

	"github.com/aleksanaa/hyphae/internal/session"
	starlark "github.com/aleksanaa/hyphae/internal/third_party/starlark/starlark"
)

//go:embed plan_mode.md
var planModePrompt string

// systemPrompt is the base system message, authored in system_prompt.md. The
// embedded file's trailing newline is trimmed once at startup so the message
// stays clean when systemExtra is appended.
//
//go:embed system_prompt.md
var systemPromptRaw string

var systemPrompt = strings.TrimSpace(systemPromptRaw)

// systemExtra is appended to systemPrompt for every session's system message. It
// holds the global user instructions and the available-skills index, assembled
// once at startup by SetSystemContext. Empty until then, so absent config files
// leave the system prompt byte-identical to the base const.
var systemExtra string

// SetSystemContext assembles the per-process system-prompt suffix from the global
// user instructions and the discovered skills. Call once at startup, before any
// turn runs.
func SetSystemContext(globalInstructions string, skills []Skill) {
	var b strings.Builder
	if s := strings.TrimSpace(globalInstructions); s != "" {
		b.WriteString("\n\nThe user has provided global instructions that apply to every session. Follow them.\n")
		b.WriteString("<user_instructions>\n")
		b.WriteString(s)
		b.WriteString("\n</user_instructions>")
	}
	b.WriteString(FormatSkills(skills))
	systemExtra = b.String()
}

// EventType classifies an agent event sent to the UI.
type EventType string

const (
	EventTextDelta      EventType = "text_delta"      // partial assistant text
	EventReasoningDelta EventType = "reasoning_delta" // partial reasoning/thinking content
	EventToolStart      EventType = "tool_start"      // tool call beginning
	EventToolDone       EventType = "tool_done"       // tool call finished
	EventDone           EventType = "done"            // turn complete
	EventError          EventType = "error"           // unrecoverable error
	EventToolApproval   EventType = "tool_approval"   // waiting for user approval
	EventSelectPrompt   EventType = "select_prompt"   // waiting for user selection (ask_user tool)
	EventConnecting     EventType = "connecting"      // establishing connection (may be retrying)
	EventPreparingTool  EventType = "preparing_tool"  // tool calls received, about to execute
	EventUsageUpdate    EventType = "usage_update"    // prompt token count updated after each LLM call
	EventStatusUpdate   EventType = "status_update"   // structured tool operation update (doing/wants/done)
)

const maxConnectAttempts = 3

// ApprovalResult is the user's response to an approval request.
type ApprovalResult struct {
	Allowed    bool
	DenyReason string
}

// ToolEvent carries info about a single tool invocation.
type ToolEvent struct {
	CallID    string
	Name      string
	Input     string // raw JSON args (reasoning stripped for display)
	Reasoning string
	Output    string // filled in on EventToolDone
	IsError   bool
	// Set for write_file and edit_file before approval.
	FilePath  string // relative path of file being changed
	DiffPatch string // unified diff of the pending change
	// Set for ask_user before EventSelectPrompt.
	SelectQuestion string
	SelectOptions  []string
}

// Event is one item from the agent event stream.
type Event struct {
	Type         EventType
	Text         string // EventTextDelta
	Tool         *ToolEvent
	Err          error               // EventError
	RespCh       chan ApprovalResult // EventToolApproval only; send exactly once
	SelectRespCh chan string         // EventSelectPrompt only; send exactly once
	// EventConnecting fields:
	Attempt     int           // current attempt number (1-based)
	MaxAttempts int           // total allowed attempts
	RetryAfter  time.Duration // >0 means waiting before the next attempt
	// EventUsageUpdate / EventDone fields:
	PromptTokens     int64   // tokens in the prompt for this LLM call (from API)
	CompletionTokens int64   // tokens generated by the model for this LLM call
	CallCost         float64 // cost of this LLM call in USD; 0 if provider didn't report it
	// EventToolStart: index of the tool status message the controller records
	// this call's structured status events against.
	// EventStatusUpdate: one structured tool operation update (doing/wants/done).
	StatusMsgIdx int
	StatusEvent  session.StatusEvent
}

// Agent orchestrates the LLM ↔ tool loop. Each agent serves a single session,
// so the run-tool namespace (persistent starlark globals) is a plain field.
type Agent struct {
	client    openai.Client
	model     string
	namespace starlark.StringDict
	grants    *grantSet // access granted at runtime via request_access; per-session
}

// New creates an Agent using the provided OpenAI client and model name.
func New(baseURL, apiKey, model string) *Agent {
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey(apiKey),
	)
	return &Agent{client: client, model: model, namespace: make(starlark.StringDict), grants: newGrantSet()}
}

// Grants returns the session's user grants (excluding the pre-registered
// builtins), for persistence and the palette.
func (a *Agent) Grants() []Grant { return a.grants.list() }

// AllGrants returns every permission the session holds, including the
// pre-registered builtins (working directory and skills directory), for display
// to the model.
func (a *Agent) AllGrants() []Grant { return a.grants.listAll() }

// LoadGrants replaces the session's grants, e.g. when resuming from storage.
func (a *Agent) LoadGrants(grants []Grant) { a.grants.load(grants) }

// AddGrant records a grant requested directly by the user (e.g. via the palette),
// normalizing the target the same way request_access does. kind is "readonly",
// "readwrite", or "web_fetch"; workDir anchors relative directory targets. It
// returns the normalized scope that was stored.
func (a *Agent) AddGrant(kind, target, workDir string) string {
	return a.grants.grant(kind, target, workDir)
}

// RevokeGrant removes one grant matching g exactly, reporting whether it existed.
func (a *Agent) RevokeGrant(g Grant) bool { return a.grants.revoke(g) }

// ModelInfo holds a model ID and its context window size (0 if unknown).
type ModelInfo struct {
	ID            string
	ContextWindow int64
}

// ListModels returns models available at the configured base URL.
// ContextWindow is populated when the provider includes "context_length" in the raw JSON.
func (a *Agent) ListModels(ctx context.Context) ([]ModelInfo, error) {
	page, err := a.client.Models.List(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]ModelInfo, len(page.Data))
	for i, m := range page.Data {
		out[i] = ModelInfo{ID: m.ID, ContextWindow: parseContextWindow(m.RawJSON())}
	}
	return out, nil
}

// parseContextWindow extracts "context_length" from a model's raw JSON (OpenAI-compatible extension).
func parseContextWindow(raw string) int64 {
	var obj struct {
		ContextLength int64 `json:"context_length"`
	}
	json.Unmarshal([]byte(raw), &obj) //nolint:errcheck
	return obj.ContextLength
}

// Send starts the agent loop from the current session state.
// The caller must have already added the user message to the session.
// Returns a channel of events; closed when the turn is complete or errored.
func (a *Agent) Send(ctx context.Context, sess *session.Session) <-chan Event {
	ch := make(chan Event, 64)
	go func() {
		defer close(ch)
		a.loop(ctx, sess, ch)
	}()
	return ch
}

func (a *Agent) loop(ctx context.Context, sess *session.Session, ch chan<- Event) {
	tools := schemas()

	for {
		if ctx.Err() != nil {
			return
		}

		msgs := buildMessages(sess)

		// Each streamed response splits into peer items: reasoning flows into a
		// lazily-created RoleThinking status; text into a RoleAssistant message.
		// Both are created only if their content actually arrives.
		thinkingIdx, assistantIdx := -1, -1
		var thinkStart time.Time
		thinkFinalized := false
		// settleThinking freezes the thinking status the moment reasoning ends
		// (when text or tools begin) so it stays visible instead of lingering as
		// an in-progress item hidden behind the streaming answer.
		settleThinking := func() {
			if thinkingIdx >= 0 && !thinkFinalized {
				sess.FinalizeThinking(thinkingIdx, int(time.Since(thinkStart).Seconds()))
				thinkFinalized = true
			}
		}

		var acc openai.ChatCompletionAccumulator
		var streamErr error
		var callCost float64
		for attempt := 1; attempt <= maxConnectAttempts; attempt++ {
			select {
			case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts}:
			case <-ctx.Done():
				return
			}

			stream := a.client.Chat.Completions.NewStreaming(ctx, openai.ChatCompletionNewParams{
				Model:         a.model,
				Messages:      msgs,
				Tools:         tools,
				StreamOptions: openai.ChatCompletionStreamOptionsParam{IncludeUsage: param.NewOpt(true)},
			})

			acc = openai.ChatCompletionAccumulator{}
			callCost = 0
			for stream.Next() {
				chunk := stream.Current()
				acc.AddChunk(chunk)
				// Extract per-call cost from raw usage JSON (e.g. OpenRouter's total_cost).
				if raw := chunk.Usage.RawJSON(); raw != "" {
					var extra struct {
						TotalCost float64 `json:"total_cost"`
					}
					if json.Unmarshal([]byte(raw), &extra) == nil && extra.TotalCost > 0 {
						callCost = extra.TotalCost
					}
				}
				if len(chunk.Choices) > 0 {
					d := chunk.Choices[0].Delta
					// Emit reasoning before content so the UI freeze order is correct.
					var raw struct {
						ReasoningContent string `json:"reasoning_content"`
					}
					if err := json.Unmarshal([]byte(d.RawJSON()), &raw); err == nil && raw.ReasoningContent != "" {
						if thinkingIdx < 0 {
							thinkingIdx = sess.AddMessage(session.Message{Role: session.RoleThinking, Partial: true})
							thinkStart = time.Now()
						}
						sess.AppendThinkingDelta(thinkingIdx, raw.ReasoningContent)
						select {
						case ch <- Event{Type: EventReasoningDelta, Text: raw.ReasoningContent}:
						case <-ctx.Done():
						}
					}
					if d.Content != "" {
						if assistantIdx < 0 {
							settleThinking() // text ends the thinking phase
							assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant, Partial: true})
						}
						sess.AppendTextDelta(assistantIdx, d.Content)
						select {
						case ch <- Event{Type: EventTextDelta, Text: d.Content}:
						case <-ctx.Done():
						}
					}
				}
			}
			streamErr = stream.Err()

			// Stop retrying on success, context cancellation, or if a partial
			// response was already received (mid-stream failures are not resumable).
			if streamErr == nil || !isRetryable(streamErr) || len(acc.Choices) > 0 {
				break
			}
			if attempt < maxConnectAttempts {
				delay := time.Duration(1<<attempt) * time.Second // 2s, 4s
				select {
				case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts, RetryAfter: delay, Err: streamErr}:
				case <-ctx.Done():
					return
				}
				select {
				case <-time.After(delay):
				case <-ctx.Done():
					return
				}
			}
		}

		// Settle thinking for tool-only rounds where no text arrived to trigger it.
		settleThinking()

		if streamErr != nil {
			if assistantIdx < 0 {
				assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant})
			}
			sess.SetMessageError(assistantIdx, streamErr)
			select {
			case ch <- Event{Type: EventError, Err: streamErr}:
			default:
			}
			return
		}

		var toolCalls []openai.ChatCompletionMessageToolCallUnion
		content := ""
		if len(acc.Choices) > 0 {
			content = acc.Choices[0].Message.Content
			toolCalls = acc.Choices[0].Message.ToolCalls
		}

		// Reconcile with the authoritative accumulator content, then settle the message.
		if content != "" && assistantIdx < 0 {
			assistantIdx = sess.AddMessage(session.Message{Role: session.RoleAssistant, Partial: true})
		}
		if assistantIdx >= 0 {
			sess.FinalizeMessage(assistantIdx, content)
		}

		// Emit usage after every LLM call so the status bar updates during tool loops.
		if pt := acc.Usage.PromptTokens; pt > 0 {
			select {
			case ch <- Event{Type: EventUsageUpdate, PromptTokens: pt, CompletionTokens: acc.Usage.CompletionTokens, CallCost: callCost}:
			case <-ctx.Done():
				return
			}
		}

		if len(toolCalls) == 0 {
			ch <- Event{Type: EventDone}
			return
		}

		select {
		case ch <- Event{Type: EventPreparingTool}:
		case <-ctx.Done():
			return
		}

		for _, tc := range toolCalls {
			if ctx.Err() != nil {
				return
			}

			te := &ToolEvent{CallID: tc.ID, Name: tc.Function.Name, Input: tc.Function.Arguments}

			// One tool status item per call; its index is where the controller
			// records this call's structured status events.
			toolIdx := sess.AddMessage(session.Message{
				Role: session.RoleTool,
				ToolUses: []session.ToolUse{{
					ID: tc.ID, Name: tc.Function.Name, Input: tc.Function.Arguments, State: "running",
				}},
			})

			select {
			case ch <- Event{Type: EventToolStart, Tool: te, StatusMsgIdx: toolIdx}:
			case <-ctx.Done():
				return
			}

			output, isErr, anyToolsRan := runScript(ctx, ch, tc.Function.Arguments, sess.WorkDir, a.namespace, a.grants)
			te.Output = output
			te.IsError = isErr
			if !anyToolsRan {
				var fallback session.StatusEvent
				if isErr {
					fallback = session.StatusEvent{Kind: session.StatusEventFailed, Verb: "run", NounP: "functions", Target: "1 function"}
				} else {
					fallback = session.StatusEvent{Kind: session.StatusEventDone, Verb: "ran", NounP: "functions", Target: "1 function"}
				}
				select {
				case ch <- Event{Type: EventStatusUpdate, StatusEvent: fallback}:
				case <-ctx.Done():
				}
			}

			sess.SetToolResult(toolIdx, tc.ID, output, isErr)

			select {
			case ch <- Event{Type: EventToolDone, Tool: te}:
			case <-ctx.Done():
				return
			}
		}

		// A tool round always continues to the model's next step, whether or not it
		// came with preamble text. The turn ends only when a response carries no
		// tool calls (handled above). Items stay in natural occurrence order.
	}
}

func buildMessages(sess *session.Session) []openai.ChatCompletionMessageParamUnion {
	msgs := []openai.ChatCompletionMessageParamUnion{openai.SystemMessage(systemPrompt + systemExtra)}

	summary, compactSeqs := sess.GetCompact()
	startIdx := 0
	if len(compactSeqs) > 0 {
		startIdx = compactSeqs[len(compactSeqs)-1] + 1
	}
	if summary != "" {
		msgs = append(msgs, openai.UserMessage("[Previous conversation summary]\n\n"+summary))
		var ap openai.ChatCompletionAssistantMessageParam
		ap.Content.OfString = openai.String("Understood. I'll continue from where we left off.")
		msgs = append(msgs, openai.ChatCompletionMessageParamUnion{OfAssistant: &ap})
	}

	history, _ := sess.Snapshot()
	msgs, _ = appendHistory(msgs, history, startIdx)
	return msgs
}

func extractReasoning(argsJSON string) (reasoning, input string) {
	var args map[string]json.RawMessage
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", argsJSON
	}
	if r, ok := args["reasoning"]; ok {
		json.Unmarshal(r, &reasoning)
	}
	return reasoning, argsJSON
}

// FormatSentLabel returns the timestamp tag for a user message.
func FormatSentLabel(t time.Time) string {
	_, secs := t.Local().Zone()
	h, mins := secs/3600, secs%3600/60
	if mins < 0 {
		mins = -mins
	}
	var tz string
	if mins != 0 {
		tz = fmt.Sprintf("UTC%+d:%02d", h, mins)
	} else {
		tz = fmt.Sprintf("UTC%+d", h)
	}
	return "<system-timestamp>The message is sent on " + t.Local().Format("2006-01-02 15:04") + " " + tz + "</system-timestamp>"
}

// SystemReminder wraps body in the <system-reminder> tags used to attach
// out-of-band context (plan mode, resume notices, working-directory changes, …)
// to the next user message. All such notices go through this so their framing
// stays consistent.
func SystemReminder(body string) string {
	return "<system-reminder>\n" + body + "\n</system-reminder>"
}

// PlanModeLabel returns the system-reminder block to append for an active plan mode turn.
func PlanModeLabel() string {
	return SystemReminder(planModePrompt)
}

// PlanModeExitLabel returns the system-reminder block to append when plan mode just ended.
func PlanModeExitLabel() string {
	return SystemReminder("Plan mode has ended. You may now make changes freely.")
}

// WorkDirChangedLabel returns the system-reminder block announcing that the
// session's working directory moved from one path to another.
func WorkDirChangedLabel(from, to string) string {
	return SystemReminder(fmt.Sprintf(
		"The working directory has changed from %s to %s. This session was resumed in a "+
			"different location than where it originally ran, so relative file paths and shell "+
			"commands now resolve against the new directory. Files, directories, and paths "+
			"referenced earlier in the conversation may no longer exist at their previous "+
			"locations, may have different contents, or may be absent entirely here. Do not "+
			"assume anything from the earlier working directory is present — verify paths (e.g. "+
			"by listing or reading them) before acting on them.",
		from, to))
}

// NamespaceClearedLabel returns the system-reminder block injected on cold session resume.
func NamespaceClearedLabel() string {
	return SystemReminder("This session was resumed from storage. The run namespace has been reset — any variables or functions defined in previous run calls are no longer available.")
}

// isRetryable returns true for transient errors that warrant a retry.
// Context cancellation and deadline are not retried.
func isRetryable(err error) bool {
	return err != nil &&
		!errors.Is(err, context.Canceled) &&
		!errors.Is(err, context.DeadlineExceeded)
}
