package agent

import (
	"context"
	_ "embed"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	openai "github.com/openai/openai-go/v3"
	"github.com/openai/openai-go/v3/option"
	"github.com/openai/openai-go/v3/packages/param"

	"github.com/aleksanaa/hyphae/internal/session"
)

//go:embed plan_mode.md
var planModePrompt string

const systemPrompt = `You are a skilled coding assistant. You help the user read, write, and reason about code.

You have tools to read files, edit files (targeted replacements), write files, list directories, run shell commands, fetch web pages, and search for text. Use them methodically: understand the task, explore when needed, make targeted changes, and verify your work.

search_files supports boolean queries (AND/OR/NOT, phrases, /regex/, ext:go filters) and returns ranked results — prefer one rich query over multiple narrow ones.

For file edits, prefer edit_file over write_file — it takes an edits array of {old_string, new_string} pairs and applies them in order. Each old_string must appear exactly once in the file; include enough surrounding context to make it unique. Use write_file only to create new files.

run_shell, web_fetch, web_search, write_file, and edit_file require user approval before executing. Always fill in the "reasoning" field with one short sentence explaining why — it is shown to the user in the approval prompt.`

// EventType classifies an agent event sent to the UI.
type EventType string

const (
	EventTextDelta      EventType = "text_delta"      // partial assistant text
	EventReasoningDelta EventType = "reasoning_delta" // partial reasoning/thinking content
	EventToolStart      EventType = "tool_start"      // tool call beginning
	EventToolDone       EventType = "tool_done"       // tool call finished
	EventDone           EventType = "done"            // turn complete
	EventError          EventType = "error"           // unrecoverable error
	EventToolApproval   EventType = "tool_approval"   // waiting for user approval
	EventSelectPrompt   EventType = "select_prompt"   // waiting for user selection (ask_user tool)
	EventConnecting     EventType = "connecting"      // establishing connection (may be retrying)
	EventPreparingTool  EventType = "preparing_tool"  // tool calls received, about to execute
	EventUsageUpdate    EventType = "usage_update"    // prompt token count updated after each LLM call
)

const maxConnectAttempts = 3

// ApprovalResult is the user's response to an approval request.
type ApprovalResult struct {
	Allowed    bool
	DenyReason string
}

// ToolEvent carries info about a single tool invocation.
type ToolEvent struct {
	CallID    string
	Name      string
	Input     string // raw JSON args (reasoning stripped for display)
	Reasoning string
	Output    string // filled in on EventToolDone
	IsError   bool
	// Set for write_file and edit_file before approval.
	FilePath  string // relative path of file being changed
	DiffPatch string // unified diff of the pending change
	// Set for ask_user before EventSelectPrompt.
	SelectQuestion string
	SelectOptions  []string
}

// Event is one item from the agent event stream.
type Event struct {
	Type         EventType
	Text         string // EventTextDelta
	Tool         *ToolEvent
	Err          error               // EventError
	RespCh       chan ApprovalResult // EventToolApproval only; send exactly once
	SelectRespCh chan string         // EventSelectPrompt only; send exactly once
	// EventConnecting fields:
	Attempt     int           // current attempt number (1-based)
	MaxAttempts int           // total allowed attempts
	RetryAfter  time.Duration // >0 means waiting before the next attempt
	// EventUsageUpdate / EventDone fields:
	PromptTokens     int64   // tokens in the prompt for this LLM call (from API)
	CompletionTokens int64   // tokens generated by the model for this LLM call
	CallCost         float64 // cost of this LLM call in USD; 0 if provider didn't report it
}

// Agent orchestrates the LLM ↔ tool loop.
type Agent struct {
	client openai.Client
	model  string
}

// New creates an Agent using the provided OpenAI client and model name.
func New(baseURL, apiKey, model string) *Agent {
	client := openai.NewClient(
		option.WithBaseURL(baseURL),
		option.WithAPIKey(apiKey),
	)
	return &Agent{client: client, model: model}
}

// ModelInfo holds a model ID and its context window size (0 if unknown).
type ModelInfo struct {
	ID            string
	ContextWindow int64
}

// ListModels returns models available at the configured base URL.
// ContextWindow is populated when the provider includes "context_length" in the raw JSON.
func (a *Agent) ListModels(ctx context.Context) ([]ModelInfo, error) {
	page, err := a.client.Models.List(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]ModelInfo, len(page.Data))
	for i, m := range page.Data {
		out[i] = ModelInfo{ID: m.ID, ContextWindow: parseContextWindow(m.RawJSON())}
	}
	return out, nil
}

// parseContextWindow extracts "context_length" from a model's raw JSON (OpenAI-compatible extension).
func parseContextWindow(raw string) int64 {
	var obj struct {
		ContextLength int64 `json:"context_length"`
	}
	json.Unmarshal([]byte(raw), &obj) //nolint:errcheck
	return obj.ContextLength
}

// Send starts the agent loop from the current session state.
// The caller must have already added the user message to the session.
// Returns a channel of events; closed when the turn is complete or errored.
func (a *Agent) Send(ctx context.Context, sess *session.Session) <-chan Event {
	ch := make(chan Event, 64)
	go func() {
		defer close(ch)
		a.loop(ctx, sess, ch)
	}()
	return ch
}

func (a *Agent) loop(ctx context.Context, sess *session.Session, ch chan<- Event) {
	tools := schemas()

	for {
		if ctx.Err() != nil {
			return
		}

		msgs := buildMessages(sess)

		sess.AddMessage(session.Message{Role: session.RoleStatus})
		assistantMsg := session.Message{Role: session.RoleAssistant, Partial: true}
		msgIdx := sess.AddMessage(assistantMsg)

		var acc openai.ChatCompletionAccumulator
		var streamErr error
		var callCost float64
		for attempt := 1; attempt <= maxConnectAttempts; attempt++ {
			select {
			case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts}:
			case <-ctx.Done():
				return
			}

			stream := a.client.Chat.Completions.NewStreaming(ctx, openai.ChatCompletionNewParams{
				Model:         a.model,
				Messages:      msgs,
				Tools:         tools,
				StreamOptions: openai.ChatCompletionStreamOptionsParam{IncludeUsage: param.NewOpt(true)},
			})

			acc = openai.ChatCompletionAccumulator{}
			callCost = 0
			for stream.Next() {
				chunk := stream.Current()
				acc.AddChunk(chunk)
				// Extract per-call cost from raw usage JSON (e.g. OpenRouter's total_cost).
				if raw := chunk.Usage.RawJSON(); raw != "" {
					var extra struct {
						TotalCost float64 `json:"total_cost"`
					}
					if json.Unmarshal([]byte(raw), &extra) == nil && extra.TotalCost > 0 {
						callCost = extra.TotalCost
					}
				}
				if len(chunk.Choices) > 0 {
					d := chunk.Choices[0].Delta
					// Emit reasoning before content so the UI freeze order is correct.
					var raw struct {
						ReasoningContent string `json:"reasoning_content"`
					}
					if err := json.Unmarshal([]byte(d.RawJSON()), &raw); err == nil && raw.ReasoningContent != "" {
						sess.AppendThinkingDelta(msgIdx, raw.ReasoningContent)
						select {
						case ch <- Event{Type: EventReasoningDelta, Text: raw.ReasoningContent}:
						case <-ctx.Done():
						}
					}
					if d.Content != "" {
						sess.AppendTextDelta(msgIdx, d.Content)
						select {
						case ch <- Event{Type: EventTextDelta, Text: d.Content}:
						case <-ctx.Done():
						}
					}
				}
			}
			streamErr = stream.Err()

			// Stop retrying on success, context cancellation, or if a partial
			// response was already received (mid-stream failures are not resumable).
			if streamErr == nil || !isRetryable(streamErr) || len(acc.Choices) > 0 {
				break
			}
			if attempt < maxConnectAttempts {
				delay := time.Duration(1<<attempt) * time.Second // 2s, 4s
				select {
				case ch <- Event{Type: EventConnecting, Attempt: attempt, MaxAttempts: maxConnectAttempts, RetryAfter: delay, Err: streamErr}:
				case <-ctx.Done():
					return
				}
				select {
				case <-time.After(delay):
				case <-ctx.Done():
					return
				}
			}
		}

		if streamErr != nil {
			sess.SetMessageError(msgIdx, streamErr)
			select {
			case ch <- Event{Type: EventError, Err: streamErr}:
			default:
			}
			return
		}

		var toolCalls []openai.ChatCompletionMessageToolCallUnion
		content := ""
		if len(acc.Choices) > 0 {
			content = acc.Choices[0].Message.Content
			toolCalls = acc.Choices[0].Message.ToolCalls
		}

		sess.FinalizeMessage(msgIdx, content, toSessionToolUses(toolCalls))

		// Emit usage after every LLM call so the status bar updates during tool loops.
		if pt := acc.Usage.PromptTokens; pt > 0 {
			select {
			case ch <- Event{Type: EventUsageUpdate, PromptTokens: pt, CompletionTokens: acc.Usage.CompletionTokens, CallCost: callCost}:
			case <-ctx.Done():
				return
			}
		}

		if len(toolCalls) == 0 {
			ch <- Event{Type: EventDone}
			return
		}

		select {
		case ch <- Event{Type: EventPreparingTool}:
		case <-ctx.Done():
			return
		}

		for _, tc := range toolCalls {
			if ctx.Err() != nil {
				return
			}

			te := &ToolEvent{CallID: tc.ID, Name: tc.Function.Name, Input: tc.Function.Arguments}

			// ask_user blocks waiting for user selection before continuing.
			if tc.Function.Name == "ask_user" {
				var args struct {
					Question string   `json:"question"`
					Options  []string `json:"options"`
				}
				json.Unmarshal([]byte(tc.Function.Arguments), &args)
				te.SelectQuestion = args.Question
				te.SelectOptions = args.Options

				sess.SetToolState(msgIdx, tc.ID, "pending")
				respCh := make(chan string, 1)
				select {
				case ch <- Event{Type: EventSelectPrompt, Tool: te, SelectRespCh: respCh}:
				case <-ctx.Done():
					return
				}
				var answer string
				select {
				case answer = <-respCh:
				case <-ctx.Done():
					return
				}
				te.Output = answer
				sess.AddMessage(session.Message{
					Role:       session.RoleTool,
					ToolResult: &session.ToolResult{ID: tc.ID, Content: answer},
				})
				sess.SetToolResult(msgIdx, tc.ID, answer, false)
				select {
				case ch <- Event{Type: EventToolDone, Tool: te}:
				case <-ctx.Done():
				}
				continue
			}

			if requiresApproval(tc.Function.Name) {
				te.Reasoning, te.Input = extractReasoning(tc.Function.Arguments)
				var diffErr error
				te.FilePath, te.DiffPatch, diffErr = computeDiffForApproval(tc.Function.Name, tc.Function.Arguments, sess.WorkDir)
				if diffErr != nil {
					errMsg := diffErr.Error()
					sess.AddMessage(session.Message{
						Role:       session.RoleTool,
						ToolResult: &session.ToolResult{ID: tc.ID, Content: errMsg, IsError: true},
					})
					sess.SetToolResult(msgIdx, tc.ID, errMsg, true)
					te.Output = errMsg
					te.IsError = true
					select {
					case ch <- Event{Type: EventToolDone, Tool: te}:
					case <-ctx.Done():
					}
					continue
				}
				sess.SetToolState(msgIdx, tc.ID, "pending")
				respCh := make(chan ApprovalResult, 1)
				select {
				case ch <- Event{Type: EventToolApproval, Tool: te, RespCh: respCh}:
				case <-ctx.Done():
					return
				}
				var approval ApprovalResult
				select {
				case approval = <-respCh:
				case <-ctx.Done():
					return
				}
				if !approval.Allowed {
					denied := "Execution denied by user."
					if approval.DenyReason != "" {
						denied += " Reason: " + approval.DenyReason
					}
					sess.AddMessage(session.Message{
						Role:       session.RoleTool,
						ToolResult: &session.ToolResult{ID: tc.ID, Content: denied, IsError: true},
					})
					sess.SetToolResult(msgIdx, tc.ID, denied, true)
					sess.SetToolState(msgIdx, tc.ID, "refused")
					te.Output = denied
					te.IsError = true
					select {
					case ch <- Event{Type: EventToolDone, Tool: te}:
					case <-ctx.Done():
					}
					continue
				}
			}

			if requiresApproval(tc.Function.Name) {
				sess.SetToolState(msgIdx, tc.ID, "running")
			}

			select {
			case ch <- Event{Type: EventToolStart, Tool: te}:
			case <-ctx.Done():
				return
			}

			output, isErr := executeTool(ctx, tc.Function.Name, tc.Function.Arguments, sess.WorkDir)
			te.Output = output
			te.IsError = isErr

			sess.AddMessage(session.Message{
				Role: session.RoleTool,
				ToolResult: &session.ToolResult{
					ID:      tc.ID,
					Content: output,
					IsError: isErr,
				},
			})
			sess.SetToolResult(msgIdx, tc.ID, output, isErr)

			select {
			case ch <- Event{Type: EventToolDone, Tool: te}:
			case <-ctx.Done():
				return
			}
		}
	}
}

func buildMessages(sess *session.Session) []openai.ChatCompletionMessageParamUnion {
	msgs := []openai.ChatCompletionMessageParamUnion{openai.SystemMessage(systemPrompt)}

	summary, compactSeqs := sess.GetCompact()
	startIdx := 0
	if len(compactSeqs) > 0 {
		startIdx = compactSeqs[len(compactSeqs)-1] + 1
	}
	if summary != "" {
		msgs = append(msgs, openai.UserMessage("[Previous conversation summary]\n\n"+summary))
		var ap openai.ChatCompletionAssistantMessageParam
		ap.Content.OfString = openai.String("Understood. I'll continue from where we left off.")
		msgs = append(msgs, openai.ChatCompletionMessageParamUnion{OfAssistant: &ap})
	}

	history, _ := sess.Snapshot()
	msgs, _ = appendHistory(msgs, history, startIdx)
	return msgs
}

func requiresApproval(name string) bool {
	switch name {
	case "run_shell", "web_fetch", "write_file", "edit_file", "web_search":
		return true
	}
	return false
}

func extractReasoning(argsJSON string) (reasoning, input string) {
	var args map[string]json.RawMessage
	if err := json.Unmarshal([]byte(argsJSON), &args); err != nil {
		return "", argsJSON
	}
	if r, ok := args["reasoning"]; ok {
		json.Unmarshal(r, &reasoning)
	}
	return reasoning, argsJSON
}

// FormatSentLabel returns the timestamp tag for a user message.
func FormatSentLabel(t time.Time) string {
	_, secs := t.Local().Zone()
	h, mins := secs/3600, secs%3600/60
	if mins < 0 {
		mins = -mins
	}
	var tz string
	if mins != 0 {
		tz = fmt.Sprintf("UTC%+d:%02d", h, mins)
	} else {
		tz = fmt.Sprintf("UTC%+d", h)
	}
	return "<system-timestamp>The message is sent on " + t.Local().Format("2006-01-02 15:04") + " " + tz + "</system-timestamp>"
}

// PlanModeLabel returns the system-reminder block to append for an active plan mode turn.
func PlanModeLabel() string {
	return "<system-reminder>\n" + planModePrompt + "\n</system-reminder>"
}

// PlanModeExitLabel returns the system-reminder block to append when plan mode just ended.
func PlanModeExitLabel() string {
	return "<system-reminder>\nPlan mode has ended. You may now make changes freely.\n</system-reminder>"
}

// isRetryable returns true for transient errors that warrant a retry.
// Context cancellation and deadline are not retried.
func isRetryable(err error) bool {
	return err != nil &&
		!errors.Is(err, context.Canceled) &&
		!errors.Is(err, context.DeadlineExceeded)
}

func toSessionToolUses(tcs []openai.ChatCompletionMessageToolCallUnion) []session.ToolUse {
	out := make([]session.ToolUse, len(tcs))
	for i, tc := range tcs {
		key, params := ParseToolDisplay(tc.Function.Name, tc.Function.Arguments)
		out[i] = session.ToolUse{
			ID: tc.ID, Name: tc.Function.Name, Input: tc.Function.Arguments,
			DisplayKey: key, DisplayParams: params,
		}
	}
	return out
}

// ParseToolDisplay extracts a summary key and ordered display params from tool JSON input.
func ParseToolDisplay(name, input string) (displayKey string, params []session.ToolParam) {
	var m map[string]json.RawMessage
	if json.Unmarshal([]byte(input), &m) != nil {
		return "", nil
	}

	fmtVal := func(raw json.RawMessage) string {
		if len(raw) > 0 && raw[0] == '[' {
			var arr []json.RawMessage
			json.Unmarshal(raw, &arr)
			return fmt.Sprintf("[%d items]", len(arr))
		}
		if len(raw) > 0 && raw[0] == '{' {
			return "{...}"
		}
		var s string
		if json.Unmarshal(raw, &s) == nil {
			if runes := []rune(s); len(runes) > 200 {
				return string(runes[:197]) + "…"
			}
			return s
		}
		return string(raw)
	}

	primary := "path"
	switch name {
	case "run_shell":
		primary = "command"
	case "web_fetch":
		primary = "url"
	case "web_search":
		primary = "query"
	case "search_files":
		primary = "pattern"
	case "ask_user":
		primary = "question"
	}
	if v, ok := m[primary]; ok {
		val := fmtVal(v)
		if runes := []rune(val); len(runes) > 50 {
			displayKey = string(runes[:47]) + "…"
		} else {
			displayKey = val
		}
		params = append(params, session.ToolParam{Key: primary, Value: val})
		delete(m, primary)
	}
	for _, k := range []string{"offset", "limit", "format", "timeout", "edits", "content"} {
		if v, ok := m[k]; ok {
			params = append(params, session.ToolParam{Key: k, Value: fmtVal(v)})
			delete(m, k)
		}
	}
	reasoning, hasReasoning := m["reasoning"]
	delete(m, "reasoning")
	for k, v := range m {
		params = append(params, session.ToolParam{Key: k, Value: fmtVal(v)})
	}
	if hasReasoning {
		params = append(params, session.ToolParam{Key: "reasoning", Value: fmtVal(reasoning)})
	}
	return
}
